### PR TITLE
Test/add tests

### PR DESCRIPTION
**Pull request by jcharkow**
# Description

Add/Update Tests

Fixes # (issue)
#112 

## Type of change
- Add tests for all structs, peakPickers and loaders
- s
- New dependencies for testing, pytest+syrupy+https://github.com/atharva-2001/syrupy-pandas-numpy/  allowing for snapshots of pandas dataframes and numpy arrays

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Pytest has been run locally on ubuntu.

# Checklist:

- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [ X] I have added tests that prove my fix is effective or that my feature works
- [X ] New and existing unit tests pass locally with my changes
- [X ] Any dependent changes have been merged and published in downstream modules

# Contents ([#114](https://github.com/Roestlab/massdash/pull/114))

### Other
- Roestlab/massseer into test/add_tests
- fix gh actions
- replace filename with runName
- more changes from filename -> runname
- update tests to work on windows
- test: remove failing tests
- resolve tests?
- make ionMobilityTest os specific
- revert ionMobilityTest.mzML to linux format
- gui bugs
- fix docs for this PR
- update snapshots
- fix readthedocs build?
- Add testing module for auto docs
- fix imports fix typo
- hopefully fix bug
- try to fix build
- update docs hopefully build
- revert to old setup

### Uncategorised!
- [TEST] add test for feature maps
- [TEST][FIX] add tests for Spectrum and Mobilogram
- [TEST] add targetedDIAConfig test
- [TEST] add generic feature tests
- Move tests to access folder
- [TEST] add test for results tsv access
- [TEST] transition TSV access
- [TEST] add TransitionPQPDataAccess
- version control snapshots
- [TEST] add Pandas Snapshot exdtension
- add new requirements for test
- [TEST] update transitionPQP for syrupy
- [TEST] update OSWDataAccess to use syrupy
- [TEST] mzMLDataAccess
- [TEST] update ResultsTSV access for new pytest format
- [TEST] TransitionTSVDataAccess with pytest+pandas
- [TEST] sqMassDataAccess update to snapshots/pytest
- [TEST] add snapshots to access tests
- [TEST] fix bug in TSVDataAccess test
- [TEST] Abstract Loaders tests
- Merge branch 'patch/refactor_plot_peak_picking' into test/add_tests
- [TEST] update sqmassloader for pytest/syrupy
- [TEST] update filepaths for test
- [TEST] update snapshots
- [TEST] create toPandasDf methods for testing
- [TEST] add MzMLDataLoader test
- [TEST] add test for SpectralLibraryLoader
- [TEST][FIX] update peakPicker tests
- [TEST] add test to ConformerPeakPicker
- [TEST] add tests for missing structs
- [TEST] Add/update file header to test files
- Add check_function() which checks/loads function in module
- [TEST] update snapshots
- [TEST][FIX] make TEST_PATH  dynamic
- Remove old print statements
- update requirements for ci/cd testing
- update README.md python compatibility version badge
- update acceptable python version range [3.9 - 3.11]
- update dtype casting of mock DF
- update dtype casting of mock DF to int64
- don't check dtype when comparing DFs
- Switch to pytest from unittest
- remove snapshottest from requirements-dev
- update ionMobility.mzML to windows file

### CODE REVIEW

**Comment by jcharkow** [comment]
@irahorecka or @singjc  would either of you be able to help with the following?

TODO:
- Needs testing on windows/mac
- Need to update github actions
-  Need to add syrupy and pytest to testing installation

**Comment by singjc** [comment]
> @irahorecka or @singjc would either of you be able to help with the following?
> 
> TODO:
> 
>     * Needs testing on windows/mac
> 
>     * Need to update github actions
> 
>     * Need to add syrupy and pytest to testing installation

@irahorecka , would you be able to help out with this?

**Comment by irahorecka** [comment]
I could work on updating the GitHub Actions - is there a list of items that need to be updated?

**Comment by jcharkow** [comment]
I am not sure exactly how it is configured right now so I don't know exactly what needs to be updated. 

My main concern is ensuring  syrupy and pytest are downloaded before the tests begin. Not sure if we should create a requirements-test or something? 

Also note I a massdash.testing that depends on syrupy. Not sure if this code should be placed in a different spot since syrupy is only needed for testing? 

> I could work on updating the GitHub Actions - is there a list of items that need to be updated?

**Comment by jcharkow** [comment]
@irahorecka any updates on this?

**Comment by irahorecka** [comment]
Hey sorry I’ve been really busy with other things. If there is a CI/CD portion I can update I’d be happy to do that. Haven’t looked into Syrupy yet. Do we need more tests?

**Comment by irahorecka** [comment]
Also, I notice we only test for Python 3.9, 3.10, and 3.11. We claim to cover 3.8 - 3.12. Should we narrow this range? I believe 3.8 isn't compatible with the Streamlit version we're using. I'm unsure about 3.12; I could give this a try right now.

[EDIT]
Actually, the current PyOpenMS only supports 3.9, 3.10, and 3.11. I'll update the PyPI specs and README accordingly.

**Comment by irahorecka** [comment]
@jcharkow @singjc - all tests passed

**Comment by jcharkow** [comment]
@irahorecka thanks for fixing this. Are we using pytest/syrupy now? I could not tell. I'm not sure what command is currently being run by github action but I am not sure if the loader tests and peak picker tests are currently being discovered.

**Comment by irahorecka** [comment]
@jcharkow No problem; and no we are using Python's default unit test library:

```python -m unittest discover -vv```

I'm currently working on using pytest. But we have a testing issue: MS dataset paths, as defined in `.ambr` files, are hard coded to your computer's path. Can we safely delete this from the `.ambr` files or would you know if we could exclude adding this attribute altogether?

```ambr
# serializer version: 1
# name: test_loadTransitionGroupFeature[INVALID-0]
  '''
  TransitionGroupFeatureCollection({
    '/home/joshua/Development/massdash_alt/massdash/test/test_data/xics/test_chrom_1.sqMass': list([
    ]),
    '/home/joshua/Development/massdash_alt/massdash/test/test_data/xics/test_chrom_2.sqMass': list([
    ]),
  })
  '''
# ---
```

**Comment by jcharkow** [comment]
good question, yes this is not ideal. maybe the current functionality does not make sense either and the dictionary key should only be the runname instead of the full file path? Alternatively we can ignore the keys and only serialize the values?

**Comment by irahorecka** [comment]
@jcharkow I raised an issue with Syrupy developers to see if it's possible to ignore the `filename` parameter when taking snapshots. I'm unsure when they'll reply, so if you'd like to merge this branch in its current state I'm okay with it.

**Comment by jcharkow** [comment]
Thanks for investing further. Thinking about it more I think that it might make sense to not use the whole path for the dictionary names to make testing easier. Then we can avoid this issue and also makes jupyter notebook interface easier.

**Comment by irahorecka** [comment]
No problem - I tried relative paths from the calling file to the data file but to no avail

**Comment by irahorecka** [comment]
I believe unit test is still useful for some tests?

**Comment by jcharkow** [comment]
> I believe unit test is still useful for some tests?

I thought that pytest could also test for uniittests and it looks like it has prettier syntax?

**Comment by irahorecka** [comment]
Hmm - not sure!

**Comment by irahorecka** [comment]
Hey @jcharkow, here's the issue I raised with Syrupy developers: https://github.com/tophat/syrupy/issues/861

I will leave the merging of this branch up to you

**Comment by jcharkow** [comment]
> Hey @jcharkow, here's the issue I raised with Syrupy developers: [tophat/syrupy#861](https://github.com/tophat/syrupy/issues/861)
> 
> I will leave the merging of this branch up to you

Thank you!

**Comment by jcharkow** [comment]
Note: there was some difficulty with tests on windows (test_MzMLDataAccess.py) because of the ionMobilityTest.mzML file not being windows compatible for OnDiscMSExperiment(). As a workaround, the file is opened as an MSExperiment() and resaved and the tests are done on the test file. 

 See the error ran into here: 
image

**Comment by jcharkow** [comment]
@singjc is this good to merge or would you like to review this before merging? @irahorecka reviewed this and said it was good to go.

**Comment by jcharkow** [comment]
Some Docs still have to be updated for this since syntax has changed however the GUI looks fine

**Comment by singjc** [comment]
> @singjc is this good to merge or would you like to review this before merging? @irahorecka reviewed this and said it was good to go.  

Yes, feel free to merge when ready.

**Pull request merged**
