### PR TITLE
refactor: combine preprocessor with conformer

### PR DESCRIPTION
**Pull request by jcharkow**
Preprocessor and conformer were requiring many of the same attributes. Instead of passing many of the attributes to one another combined the classes. Preprocessor methods are private because they are more complex.

Also move some preprocessor functions to transformations

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] This change requires a documentation update

# How Has This Been Tested?
Tested using the GUI

# Contents ([#101](https://github.com/Roestlab/massdash/pull/101))

### Other
- combine preprocessor with conformer

### CODE REVIEW

**Review by singjc — APPROVED** [review]
Looks good. Makes sense to just merge the preprocessing into peak picking.

**Comment by jcharkow** [comment]
@irahorecka do you know why this is failing on mac?

**Comment by irahorecka** [comment]
Hi - is this still an issue? What's breaking?

**Comment by singjc** [comment]
I don't think it's an issue now, just had to re-run the test

**Comment by jcharkow** [comment]
> Hi - is this still an issue? What's breaking?

sorry yes it was failing before but now it is good

**Pull request merged**
